import math

def SetGeometricParameters(model,L,r):
    smoothingLength = 1.3*r*2;
    Kappa = 2.0;
    KappaH = smoothingLength*Kappa;
    model.SetParameter("GridSizeX","%d" % math.floor(L[0]/KappaH));
    model.SetParameter("GridSizeY","%d" % math.floor(L[1]/KappaH));
    model.SetParameter("GridSizeZ","%d" % math.floor(L[2]/KappaH));
    model.SetParameter("Lx","%f" % L[0]);
    model.SetParameter("Ly","%f" % L[1]);
    model.SetParameter("Lz","%f" % L[2]);
    model.SetParameter("SmoothingLength","%f" % (1.3*r*2));
    model.SetParameter("InitialParticleSeparation","%f" % (r*2));

def SetDefaultParameters(model,L,r):
    SetGeometricParameters(model,L,r);
    model.SetParameter("ParticlesPerCell","100");
    model.SetParameter("MaxSteps","10000");
    model.SetParameter("Mass","1");
    model.SetParameter("Epsilon","0.5");
    model.SetParameter("ViscEtq","test");
    model.SetParameter("ViscAlpha","test");
    model.SetParameter("ViscBeta","test");
    model.SetParameter("DTime","test");
    model.SetParameter("SpeedSound","test");
    model.SetParameter("initialDensity","test");
    model.SetParameter("SmoothingKernelFunc","test");
    model.SetParameter("Dim","test");
    model.SetParameter("AlgorithmSPH","test");
    model.SetParameter("BoundaryUpdateStep","1");
    model.SetParameter("limitBoundaryDensity","test");
    model.SetParameter("IsExternalForce","test");
    model.SetParameter("IsAverageVelocity","test");
    model.SetParameter("IsVisc","test");
    model.SetParameter("IsViscArtificial","test");
    model.SetParameter("IsNoSlip","test");
    model.SetParameter("IsSurfaceTension","test");
    model.SetParameter("IsDeltaSPH","test");
    model.SetParameter("delta","test");
    model.SetParameter("GravityX","test");
    model.SetParameter("GravityY","test");
    model.SetParameter("GravityZ","test");
    model.SetParameter("IsPeriodicBoundaryX","test");
    model.SetParameter("IsPeriodicBoundaryY","test");
    model.SetParameter("IsPeriodicBoundaryZ","test");
    model.SetParameter("IsLaminarVisc","test");
    model.SetParameter("IsSpsVisc","test");
    model.SetParameter("EOS","2");
    model.SetParameter("MonaghanB","test");
    model.SetParameter("MonaghanGamma","test");
    model.SetParameter("DensityFunction","test");
    model.SetParameter("IsRepulsiveForceBC","test");
    model.SetParameter("IsShepard","test");
    model.SetParameter("ShepardStep","test");
    model.SetParameter("Viscosity","test");
    model.SetParameter("MovingBoundaryAmplitudeX","test");
    model.SetParameter("MovingBoundaryAmplitudeY","test");
    model.SetParameter("MovingBoundaryAmplitudeZ","test");
    model.SetParameter("MovingBoundaryFrequencyX","test");
    model.SetParameter("MovingBoundaryFrequencyY","test");
    model.SetParameter("MovingBoundaryFrequencyZ","test");
    model.SetParameter("MovingBoundaryPhaseX","test");
    model.SetParameter("MovingBoundaryPhaseY","test");
    model.SetParameter("MovingBoundaryPhaseZ","test");
    model.SetParameter("MovingBoundaryShiftX","test");
    model.SetParameter("MovingBoundaryShiftY","test");
    model.SetParameter("MovingBoundaryShiftZ","test");
    model.SetParameter("ShearModulus","test");
    model.SetParameter("BulkModulus","test");
    model.SetParameter("PoissonRatio","test");
    model.SetParameter("YoungModulus","test");
    model.SetParameter("deltaRmat","%f" % (1e-12 * 1.667e-05));
    model.SetParameter("yieldTensileStrength","test");
    model.SetParameter("KDamage","test");
    model.SetParameter("MDamage","test");
    model.SetParameter("IsSolids","test");
    model.SetParameter("IsDamage","test");
    model.SetParameter("IsPlasticityCorr","test");
    model.SetParameter("IsTensileInstCorr","test");
    model.SetParameter("IsFlags","test");
    model.SetParameter("IsReverseMoving","test");
    model.SetParameter("IsDensityBound","test");
    model.SetParameter("IsAssociatedFlowRule","test");
    model.SetParameter("IsDPbased","test");
    model.SetParameter("IsDamping","test");
    model.SetParameter("IsAlternateViscArtificial","test");
    model.SetParameter("ViscAlphamin","test");
    model.SetParameter("ViscAlphamax","test");
    model.SetParameter("IsContactForce","test");
    model.SetParameter("IsForcedBoundaries","test");
    model.SetParameter("IsStressedBoundaries","test");
    model.SetParameter("IsPlaneStress","test");
    model.SetParameter("IsPlaneStrain","test");
    model.SetParameter("IsPlaneStrain2PlaneStress","test");
    model.SetParameter("IsElastoPlasticDamage","test");
    model.SetParameter("IsDruckerPragerPlasticity","test");
    model.SetParameter("DPcohesionSoftening","test");
    model.SetParameter("DPYieldsurface","test");
    model.SetParameter("IsDPApexCriterion","test");
    model.SetParameter("IsDPTensileCrackingCriterion","test");
    model.SetParameter("BoundaryNormalTolerance","test");
    model.SetParameter("RankineCriticalStress","test");
    model.SetParameter("StVenantCriticalStrain","test");
    model.SetParameter("Cohesion","test");
    model.SetParameter("FrictionAngle","test");
    model.SetParameter("DilatancyAngle","test");
    model.SetParameter("YieldShearStrength","test");
    model.SetParameter("YieldCompressiveStrength","test");
    model.SetParameter("YieldBiaxialCompressiveStrength","test");
    model.SetParameter("CohnPt1","test");
    model.SetParameter("CohnPt2","test");
    model.SetParameter("PlastStrainPt1","test");
    model.SetParameter("PlastStrainPt2","test");
    model.SetParameter("EpsilonRmat","0.1");
    model.SetParameter("Cg","test");
    model.SetParameter("PlasticityModel","test");
    model.SetParameter("DamageModel","test");
    model.SetParameter("DampingCoef","0.02");
    model.SetParameter("IsImposedDisplacement","test");
    model.SetParameter("Impdx","test");
    model.SetParameter("Impdy","test");
    model.SetParameter("Impdz","test");
    model.SetParameter("IsFloatingObjectRotation","test");
    model.SetParameter("FloatingObjectAppliedFx","test");
    model.SetParameter("FloatingObjectAppliedFy","test");
    model.SetParameter("FloatingObjectAppliedFz","test");
    model.SetParameter("FloatingObjectAppliedForceRampTime","test");
    model.SetParameter("IsFloatingObjectMotionX","test");
    model.SetParameter("IsFloatingObjectMotionY","test");
    model.SetParameter("IsFloatingObjectMotionZ","test");
    model.SetParameter("Movfx","test");
    model.SetParameter("Movfy","test");
    model.SetParameter("Movfz","test");
    model.SetParameter("Movsxx","test");
    model.SetParameter("Movsxy","test");
    model.SetParameter("Movsyy","test");
    model.SetParameter("Movsyz","test");
    model.SetParameter("Movsxz","test");
    model.SetParameter("Movszz","test");
    model.SetParameter("BoundariesRampTime","test");
    model.SetParameter("Cracksxx","test");
    model.SetParameter("Cracksxy","test");
    model.SetParameter("Cracksyy","test");
    model.SetParameter("Cracksyz","test");
    model.SetParameter("Cracksxz","test");
    model.SetParameter("Crackszz","test");
    model.SetParameter("CrackLength","test");
    model.SetParameter("CrackThickness","test");
    model.SetParameter("CrackX","test");
    model.SetParameter("CrackY","test");
    model.SetParameter("CrackZ","test");
    model.SetParameter("ReverseMovingX","test");
    model.SetParameter("ReverseMovingY","test");
    model.SetParameter("ReverseMovingZ","test");
    model.SetParameter("IsCrack","test");
    model.SetParameter("IsFloatingObject","test");
    model.SetParameter("IsBoundaryForce","test");
    model.SetParameter("BoundaryForceMinLimit","test");
    model.SetParameter("BoundaryForceMaxLimit","test");
    model.SetParameter("IntegrationScheme","1");
    model.SetParameter("VerletStep","40");
